# Generated by Django 5.1.4 on 2025-01-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
