# Generated by Django 5.1.4 on 2025-01-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
