# Generated by Django 5.1.4 on 2025-01-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
