# Generated by Django 5.1.4 on 2025-01-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
