# Generated by Django 5.1.4 on 2025-01-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
