# Generated by Django 5.1.4 on 2025-01-19 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_subscription_amount_subscription_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_id',
        ),
    ]
