# Generated by Django 5.1.4 on 2025-01-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
