# Generated by Django 5.1.4 on 2025-01-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
